spring:
  cloud:
    stream:
      bindings:
        input:
          destination: javaeg-stream
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: <host>
                port: <port>
                username: <username>
                password: <password>
                virtual-host: /
